Add logging control to set operation power
ham2k/app-polo pull request #35
Opened 2024-06-21 01:51 UTC by alduhoo

Adds a logging field to set operation's power and persists it for new QSOs

2024-07-02 13:21 UTC, sd requested changes
This looks good, but I think `pwr` should actually be part of `vfo`, and not abbreviated, like `vfo.power`.

Can you update the PR? Thanks!

2024-07-02 13:24 UTC, sd commented
Can you send me an email to sd@notso.net, or contact me on the Ham2k discord?

2024-07-03 07:17 UTC, alduhoo commented on src/screens/OperationScreens/OpLoggingTab/components/LoggingPanel/SecondaryExchangePanel/TxPowerControl.jsx
> +        fieldId={'txPwr'}
I think this needs to be `power` so the edit qso screen can display the proper value. I'll rename it.

2024-07-19 11:40 UTC, sd approved these changes

2024-07-19 11:40 UTC, merged